### PR TITLE
Remove runtime dependency on pbr

### PR DESCRIPTION
**Pull request by dtantsur**
Pbr is a very heavy package to depend on. It requires git-core, which is
16 MiB on my Fedora. We only use it to detect the version, which can be
done without pbr by any consumer (e.g. with importlib_metadata).

### CODE REVIEW

**Comment by dtantsur** [comment]
I can, of course, provide an alternative implementation using `importlib_metadata`, but I'm not sure how useful it is.

**Review by elfosardo — APPROVED** [review]

**Comment by ErwanAliasr1** [comment]
Can you rebase please ?

**Review by ErwanAliasr1 — APPROVED** [review]

**Comment by elfosardo** [comment]
@dtantsur this needs a rebase

**Comment by dtantsur** [comment]
There was no conflict, weird..

**Pull request merged**
