### PR TITLE
Enabling docs testing in travis

### PR DESCRIPTION
**Pull request by elfosardo**
Reviewed doc requirements and configuration.
Removed unmaintained oslosphinx in preparation of moving to
openstackdocstheme.
Removed general Babel req and added to testing.
Fixed sphinx, Babel and mock version requirements to align with
latest Python 3.x versions.

### CODE REVIEW

**Comment by dtantsur** [comment]
What's the reason of removing 3.5? It doesn't seem EOL yet. I could understand replacing it with 3.8.

**Comment by elfosardo** [comment]
@dtantsur mainly based on download stats per version

```pypinfo --days 100 --percent hardware pyversion

| python_version | percent | download_count |
| -------------- | ------- | -------------- |
| 2.7            |  48.58% |            103 |
| 3.7            |  24.53% |             52 |
| 3.6            |  21.23% |             45 |
| 3.5            |   4.25% |              9 |
| 3.8            |   0.94% |              2 |
| 3.4            |   0.47% |              1 |
| Total          |         |            212 |```

I'm more than happy to convert that to python 3.8, I think we'll see an increase of downloads for that version in the next months, while 3.5 version should decrease more and more

**Comment by dtantsur** [comment]
Then let's also drop 3.5 in that other patch to make it clear in the history?

**Comment by elfosardo** [comment]
@dtantsur sounds good

**Comment by dtantsur** [comment]
It doesn't seem to do anything on python 3: https://travis-ci.org/redhat-cip/hardware/jobs/614627747#L199. Is it intended?

**Comment by elfosardo** [comment]
@dtantsur all the tests except for unit tests run on Python 2.7 only at the moment.
This is due to how the script in .travis.yml works.
The plan would be modifying it in a follow up so all the tests run with all the Python versions.

**Comment by dtantsur** [comment]
Okay, let's not forget to do it.

**Pull request merged**
