### PR TITLE
Add meminfo module

### LINKED ISSUE #162: get_ddr_timing should use i2ctools
The command used to get the ddr timings (ddr-timings-$ARCH) has been lost in time and it's not really supported anymore [1]
We could migrate the ddr timing detection mechanism to a common easily available tool like decode-dimms, included in the i2c-tools suite.
It provides a nice output that can be easily parsed, here's an example:
`decode-dimms --side-by-side
# decode-dimms version $Revision$

Memory Serial Presence Detect Decoder
By Philip Edelbrock, Christian Zuckschwerdt, Burkart Lingner,
Jean Delvare, Trent Piepho and others

Decoding EEPROM                                  8-0050           8-0051
Guessing DIMM is in                              bank 1           bank 2

---=== SPD EEPROM Information ===---
EEPROM CRC of bytes 0-125                        OK (0x64DE)
# of bytes written to SDRAM EEPROM               384
Total number of bytes in EEPROM                  512
Fundamental Memory type                          DDR4 SDRAM
SPD Revision                                     1.1
Module Type                                      SO-DIMM
EEPROM CRC of bytes 128-253                      OK (0x2355)

---=== Memory Characteristics ===---
Maximum module speed                             2400 MHz (PC4-19200)
Size                                             16384 MB
Banks x Rows x Columns x Bits                    16 x 16 x 10 x 64
SDRAM Device Width                               8 bits
Ranks                                            2
Rank Mix                                         Symmetrical
AA-RCD-RP-RAS (cycles)                           17-17-17-39
Supported CAS Latencies                          18T, 17T, 16T, 15T, 14T, 13T, 12T, 11T, 10T

---=== Timings at Standard Speeds ===---
AA-RCD-RP-RAS (cycles) as DDR4-2400              17-17-17-39
AA-RCD-RP-RAS (cycles) as DDR4-2133              15-15-15-35
AA-RCD-RP-RAS (cycles) as DDR4-1866              13-13-13-30
AA-RCD-RP-RAS (cycles) as DDR4-1600              11-11-11-26

---=== Timing Parameters ===---
Minimum Cycle Time (tCKmin)                      0.833 ns
Maximum Cycle Time (tCKmax)                      1.600 ns
Minimum CAS Latency Time (tAA)                   13.750 ns
Minimum RAS to CAS Delay (tRCD)                  13.750 ns
Minimum Row Precharge Delay (tRP)                13.750 ns
Minimum Active to Precharge Delay (tRAS)         32.000 ns
Minimum Active to Auto-Refresh Delay (tRC)       45.750 ns
Minimum Recovery Delay (tRFC1)                   350.000 ns
Minimum Recovery Delay (tRFC2)                   260.000 ns
Minimum Recovery Delay (tRFC4)                   160.000 ns
Minimum Four Activate Window Delay (tFAW)        21.000 ns
Minimum Row Active to Row Active Delay (tRRD_S)  3.300 ns
Minimum Row Active to Row Active Delay (tRRD_L)  4.900 ns
Minimum CAS to CAS Delay (tCCD_L)                5.000 ns
Minimum Write Recovery Time (tWR)                15.000 ns
Minimum Write to Read Time (tWTR_S)              2.500 ns
Minimum Write to Read Time (tWTR_L)              7.500 ns

---=== Other Information ===---
Package Type                                     Monolithic
Maximum Activate Count                           Unlimited
Post Package Repair                              One row per bank group
Soft PPR                                         Supported
Module Nominal Voltage                           1.2 V
Thermal Sensor                                   No

---=== Physical Characteristics ===---
Module Height                                    30 mm
Module Thickness                                 2 mm front, 2 mm back
Module Reference Card                            E revision 1

---=== Manufacturer Data ===---
Module Manufacturer                              SK Hynix
DRAM Manufacturer                                SK Hynix
Manufacturing Location Code                      0x01
Manufacturing Date                               2018-W37
Assembly Serial Number                           0x2D37BA35       0x2D37E675
Part Number                                      HMA82GS6AFR8N-UH    

Number of SDRAM DIMMs detected and decoded: 2`

[1] https://github.com/redhat-cip/edeploy/blob/master/build/sources/timings.c

### PR DESCRIPTION
**Pull request by elfosardo**
Use i2ctools to get info on memory.

Closes #162

### CODE REVIEW

**Comment by ErwanAliasr1** [comment]
The change is valid but I think we should drop this part. This information is not reliable. It uses legacy registers that were wrong on some on my hosts. I do think no one uses this part.

**Comment by ErwanAliasr1** [comment]
I see your proposal around i2c-tools which has some interest to report the actual capability of the dimm but not how the memory controller is configured.
This code was about the memory controller which is very vendor/product dependant.
So switch to #162 would be way better

**Comment by elfosardo** [comment]
@ErwanAliasr1 do you think we should just remove this code then?
The conversion to i2c-tools is a big change and I thought to extract the old code from detect.py first.

**Comment by ErwanAliasr1** [comment]
@elfosardo I imlplemented this when I was at enovance for my own usage. I'm pretty sure no one knows where this tool is located today, so the code is dead and useless. I'd vote for dropping this part.

**Comment by elfosardo** [comment]
removing the code in #164
I'll rebase this on top of that and use it to use i2ctools to get the memory info

**Comment by dtantsur** [comment]
https://github.com/redhat-cip/hardware/pull/164

**Pull request closed without merging**
