### PR TITLE
Cosmetic change to adapt to new pep8 style

### PR DESCRIPTION
**Pull request by elfosardo**
First of a series of cosmetic changes to migrate to new pep8 style.
The main change is cutting the lines to less than 80 characters.
More style changes may be applied depending on the module.

This patch does not include any functional change.

### CODE REVIEW

**Comment by dtantsur** [comment]
Could you make the CI gate on this? Otherwise it's useless.

**Comment by elfosardo** [comment]
I could, but I think that would mean change tox.ini and so applying the change to the entire code at the same time.
No problem for me, it's basically an automated change, it just becomes a bit bigger to review.

**Comment by dtantsur** [comment]
How big? I'm inclined to do it in one shot, unless it's really crazy (hundreds of changes).

**Comment by elfosardo** [comment]
If we consider only the line length changes, definitely not hundreds.
Some changes are also fixed by #95 with the move of all the strings to a different file, so that should be merged first anyway; smart_utils_results.py needs the same treatment for the migration to constants, little impact anyway and I can add it to #94 and wait for the merge.
If we add the docstrings changes for correct format (it's correcting ' to " and add parameters and other stuff), then we go up in numbers, but we can exclude them at the beginning and add proper docstrings module by module in future patches.

**Comment by tbreeds** [comment]
Looks good to me.

Once we complete all the changes we've talked about in https://github.com/redhat-cip/hardware/issues/84 I'm totally in favor of enforcing pep8 in travis

**Comment by elfosardo** [comment]
@dtantsur  @tbreeds  please let me know if there is anything more to do to be able to move forward with this

**Pull request merged**
