### PR TITLE
Add support for Python 3.9

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Review by dtantsur — APPROVED** [review]
Btw we should migrate away from travis, it will become paid eventually.

**Comment by elfosardo** [comment]
> Btw we should migrate away from travis, it will become paid eventually.

they still have a free plan, but I'm looking at alternatives

**Comment by dtantsur** [comment]
Per the initial [announcement](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) their free plan will just give you some amount of "dollars" that you can spend. Then you can request more, maybe they'll give you, maybe not. They might have backed out from this strategy in the [latest post](https://blog.travis-ci.com/oss-announcement).

**Comment by elfosardo** [comment]
thanks @dtantsur , I saw that, in theory it should be enough for this project, but I'm interested in doing something with github actions or different tools/solutions.
I will open an issue for this so we can discuss there.

**Pull request merged**
