### PR TITLE
Drop Python 3.5 in favor of Python 3.8

### PR DESCRIPTION
**Pull request by elfosardo**
This patch drops support and testing for Python 3.5 in favor of
Python 3.8
Also adding docs env to tox.ini as follow-up to #110

### CODE REVIEW

**Comment by dtantsur** [comment]
Doesn't seem to work in the CI

**Comment by elfosardo** [comment]
@dtantsur Python 3.8 is more strict on certain behaviours (iterators vs list)
going to fix it here if that's ok for you

**Comment by dtantsur** [comment]
Totally

**Comment by elfosardo** [comment]
@dtantsur I'm trying to respect the fact that changing an item during iteration is not exactly a best practice and in Python 3.8 becomes basically forbidden, that's why we're seeing the error in travis with that version and not with others
in case of iteration through dict items, I do a shallow copy of the dict, iterate through it and modify the original
in case of iteration through keys, I transform the keys in list (instead of an iterator and instead of being part of the dict) to be able to work on the dict afterwards
both these methods are common practice used in Python 3.8 to avoid the more restricted limitation

**Comment by tbreeds** [comment]
```
$ pypinfo hardware pyversion
Served from cache: False
Data processed: 86.04 GiB
Data billed: 86.04 GiB
Estimated cost: $0.43

| python_version | download_count |
| -------------- | -------------- |
| 2.7            |             27 |
| 3.6            |             23 |
| 3.7            |             14 |
| 3.5            |              2 |
| 3.8            |              1 |
| Total          |             67 |
```


So yeah I think we can drop py3.5 support

**Pull request merged**
