### PR TITLE
Adding proper coverage test

### PR DESCRIPTION
**Pull request by elfosardo**
Fixing typo in .coveragerc
Adding "cover" and ".stestr" to .gitignore
Adding correct  .stestr.conf
Removing outdated check-coverage.sh
Adding correct coverage configuration to tox.ini

### CODE REVIEW

**Comment by ErwanAliasr1** [comment]
If you could prefix your commits with the items you change, that would be lovely.
Thx !

**Comment by elfosardo** [comment]
@ErwanAliasr1 I've added a list to the top comment

**Comment by dtantsur** [comment]
Should we add `stestr` to requirements?

**Comment by elfosardo** [comment]
@dtantsur I think oslotest in test-requirements covers that
we could add it anyway if we need to set a specific version, of course compatible with oslotest requirements

**Comment by dtantsur** [comment]
We need to add explicitly everything that we use explicitly. So if we call `stestr` somewhere we need it in `test-requirements` even if we have `oslotest` (which I'm not entirely sure we need).

**Comment by elfosardo** [comment]
@dtantsur I guess it is a bit overkill to add the entire oslotest just for stestr :)
I've replaced oslotest with stestr in test-requirements

**Pull request merged**
